# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-29 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_borrow_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrowed_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
